# Generated by Django 4.2 on 2025-03-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_flight_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='generated_narrative',
            field=models.TextField(blank=True),
        ),
    ]
