# Generated by Django 6.0.8 on 2026-10-05 04:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0005_alter_flight_distance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="approaches",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flight",
            name="cross_country",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flight",
            name="day_landings",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flight",
            name="dual_received_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="flight",
            name="instrument_time",
            field=models.DurationField(
                default=datetime.timedelta(0), help_text="Actual instrument conditions"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="is_simulator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flight",
            name="narrative",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="narrative_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="night_landings",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flight",
            name="night_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="flight",
            name="pic_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="flight",
            name="sic_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="flight",
            name="simulated_instrument_time",
            field=models.DurationField(
                default=datetime.timedelta(0), help_text="Under the hood"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="weather_conditions",
            field=models.TextField(blank=True, help_text="Usually the departure METAR"),
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration", models.CharField(max_length=10)),
                (
                    "type_code",
                    models.CharField(
                        blank=True,
                        help_text="ICAO type designator, e.g. C172",
                        max_length=4,
                    ),
                ),
                ("make_model", models.CharField(blank=True, max_length=60)),
                (
                    "aircraft_class",
                    models.CharField(
                        choices=[
                            ("SEL", "Single-engine land"),
                            ("MEL", "Multi-engine land"),
                            ("SES", "Single-engine sea"),
                            ("MES", "Multi-engine sea"),
                            ("HELICOPTER", "Helicopter"),
                            ("GLIDER", "Glider"),
                            ("OTHER", "Other"),
                        ],
                        default="SEL",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "maintenance_interval_hours",
                    models.PositiveIntegerField(default=100),
                ),
                ("last_maintenance_at", models.DateTimeField(blank=True, null=True)),
                ("annual_due", models.DateField(blank=True, null=True)),
                ("grounded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircraft",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "aircraft",
                "ordering": ["registration"],
            },
        ),
        migrations.AddField(
            model_name="flight",
            name="aircraft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flights",
                to="flights.aircraft",
            ),
        ),
        migrations.AddIndex(
            model_name="flight",
            index=models.Index(
                fields=["user", "-departure_time"],
                name="flights_fli_user_id_cf7c47_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraft",
            constraint=models.UniqueConstraint(
                fields=("user", "registration"), name="unique_registration_per_user"
            ),
        ),
    ]
