# Generated by Django 6.0.8 on 2026-10-05 04:39

from django.db import migrations


def link_aircraft(apps, schema_editor):
    """Create an Aircraft for every registration already in a user's logbook."""
    Aircraft = apps.get_model('flights', 'Aircraft')
    Flight = apps.get_model('flights', 'Flight')
    pairs = Flight.objects.values_list('user_id', 'registration_number').distinct()
    for user_id, registration in pairs:
        reg = registration.strip().upper()
        aircraft, _ = Aircraft.objects.get_or_create(user_id=user_id, registration=reg)
        Flight.objects.filter(user_id=user_id, registration_number=registration).update(
            aircraft=aircraft, registration_number=reg,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0006_aircraft_and_logbook_columns"),
    ]

    operations = [
        migrations.RunPython(link_aircraft, migrations.RunPython.noop),
    ]
