# Generated by Django 6.0.8 on 2026-10-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0007_link_existing_aircraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
