# Generated by Django 6.0.8 on 2026-10-06 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0008_flight_is_draft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="narrative",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="narrative_generated_at",
        ),
    ]
