# Generated by Django 6.0.8 on 2026-10-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="customuser",
            name="home_airport",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
