# Generated by Django 6.0.8 on 2026-10-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="instructor_certificate_expires",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="instructor_certificate_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
