# Generated by Django 6.0.8 on 2026-10-05 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instruction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="withdrawal_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="signature",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Endorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor_name", models.CharField(max_length=300)),
                ("certificate_number", models.CharField(max_length=20)),
                ("certificate_expires", models.DateField(blank=True, null=True)),
                ("kind", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=120)),
                ("text", models.TextField()),
                (
                    "aircraft",
                    models.CharField(
                        blank=True,
                        help_text="Make and model, where the endorsement names one",
                        max_length=60,
                    ),
                ),
                ("given_on", models.DateField()),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawal_reason", models.TextField(blank=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endorsements_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-given_on", "-signed_at", "-pk"],
            },
        ),
    ]
